package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPoExample.Criteria;
import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPoExample.Criterion;
import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class RegionPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    public String insertSelective(RegionPo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("region_region");
        
        if (row.getPid() != null) {
            sql.VALUES("`pid`", "#{pid,jdbcType=BIGINT}");
        }
        
        if (row.getLevel() != null) {
            sql.VALUES("`level`", "#{level,jdbcType=TINYINT}");
        }
        
        if (row.getAreaCode() != null) {
            sql.VALUES("`area_code`", "#{areaCode,jdbcType=VARCHAR}");
        }
        
        if (row.getZipCode() != null) {
            sql.VALUES("`zip_code`", "#{zipCode,jdbcType=VARCHAR}");
        }
        
        if (row.getCityCode() != null) {
            sql.VALUES("`city_code`", "#{cityCode,jdbcType=CHAR}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("`name`", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getShortName() != null) {
            sql.VALUES("`short_name`", "#{shortName,jdbcType=VARCHAR}");
        }
        
        if (row.getMergerName() != null) {
            sql.VALUES("`merger_name`", "#{mergerName,jdbcType=VARCHAR}");
        }
        
        if (row.getPinyin() != null) {
            sql.VALUES("`pinyin`", "#{pinyin,jdbcType=VARCHAR}");
        }
        
        if (row.getLng() != null) {
            sql.VALUES("`lng`", "#{lng,jdbcType=DECIMAL}");
        }
        
        if (row.getLat() != null) {
            sql.VALUES("`lat`", "#{lat,jdbcType=DECIMAL}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("`status`", "#{status,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    public String selectByExample(RegionPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`pid`");
        sql.SELECT("`level`");
        sql.SELECT("`area_code`");
        sql.SELECT("`zip_code`");
        sql.SELECT("`city_code`");
        sql.SELECT("`name`");
        sql.SELECT("`short_name`");
        sql.SELECT("`merger_name`");
        sql.SELECT("`pinyin`");
        sql.SELECT("`lng`");
        sql.SELECT("`lat`");
        sql.SELECT("`status`");
        sql.SELECT("`creator_id`");
        sql.SELECT("`creator_name`");
        sql.SELECT("`modifier_id`");
        sql.SELECT("`modifier_name`");
        sql.SELECT("`gmt_create`");
        sql.SELECT("`gmt_modified`");
        sql.FROM("region_region");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        RegionPo row = (RegionPo) parameter.get("row");
        RegionPoExample example = (RegionPoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("region_region");
        
        if (row.getId() != null) {
            sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getPid() != null) {
            sql.SET("`pid` = #{row.pid,jdbcType=BIGINT}");
        }
        
        if (row.getLevel() != null) {
            sql.SET("`level` = #{row.level,jdbcType=TINYINT}");
        }
        
        if (row.getAreaCode() != null) {
            sql.SET("`area_code` = #{row.areaCode,jdbcType=VARCHAR}");
        }
        
        if (row.getZipCode() != null) {
            sql.SET("`zip_code` = #{row.zipCode,jdbcType=VARCHAR}");
        }
        
        if (row.getCityCode() != null) {
            sql.SET("`city_code` = #{row.cityCode,jdbcType=CHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("`name` = #{row.name,jdbcType=VARCHAR}");
        }
        
        if (row.getShortName() != null) {
            sql.SET("`short_name` = #{row.shortName,jdbcType=VARCHAR}");
        }
        
        if (row.getMergerName() != null) {
            sql.SET("`merger_name` = #{row.mergerName,jdbcType=VARCHAR}");
        }
        
        if (row.getPinyin() != null) {
            sql.SET("`pinyin` = #{row.pinyin,jdbcType=VARCHAR}");
        }
        
        if (row.getLng() != null) {
            sql.SET("`lng` = #{row.lng,jdbcType=DECIMAL}");
        }
        
        if (row.getLat() != null) {
            sql.SET("`lat` = #{row.lat,jdbcType=DECIMAL}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{row.status,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("region_region");
        
        sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        sql.SET("`pid` = #{row.pid,jdbcType=BIGINT}");
        sql.SET("`level` = #{row.level,jdbcType=TINYINT}");
        sql.SET("`area_code` = #{row.areaCode,jdbcType=VARCHAR}");
        sql.SET("`zip_code` = #{row.zipCode,jdbcType=VARCHAR}");
        sql.SET("`city_code` = #{row.cityCode,jdbcType=CHAR}");
        sql.SET("`name` = #{row.name,jdbcType=VARCHAR}");
        sql.SET("`short_name` = #{row.shortName,jdbcType=VARCHAR}");
        sql.SET("`merger_name` = #{row.mergerName,jdbcType=VARCHAR}");
        sql.SET("`pinyin` = #{row.pinyin,jdbcType=VARCHAR}");
        sql.SET("`lng` = #{row.lng,jdbcType=DECIMAL}");
        sql.SET("`lat` = #{row.lat,jdbcType=DECIMAL}");
        sql.SET("`status` = #{row.status,jdbcType=TINYINT}");
        sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        
        RegionPoExample example = (RegionPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(RegionPo row) {
        SQL sql = new SQL();
        sql.UPDATE("region_region");
        
        if (row.getPid() != null) {
            sql.SET("`pid` = #{pid,jdbcType=BIGINT}");
        }
        
        if (row.getLevel() != null) {
            sql.SET("`level` = #{level,jdbcType=TINYINT}");
        }
        
        if (row.getAreaCode() != null) {
            sql.SET("`area_code` = #{areaCode,jdbcType=VARCHAR}");
        }
        
        if (row.getZipCode() != null) {
            sql.SET("`zip_code` = #{zipCode,jdbcType=VARCHAR}");
        }
        
        if (row.getCityCode() != null) {
            sql.SET("`city_code` = #{cityCode,jdbcType=CHAR}");
        }
        
        if (row.getName() != null) {
            sql.SET("`name` = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getShortName() != null) {
            sql.SET("`short_name` = #{shortName,jdbcType=VARCHAR}");
        }
        
        if (row.getMergerName() != null) {
            sql.SET("`merger_name` = #{mergerName,jdbcType=VARCHAR}");
        }
        
        if (row.getPinyin() != null) {
            sql.SET("`pinyin` = #{pinyin,jdbcType=VARCHAR}");
        }
        
        if (row.getLng() != null) {
            sql.SET("`lng` = #{lng,jdbcType=DECIMAL}");
        }
        
        if (row.getLat() != null) {
            sql.SET("`lat` = #{lat,jdbcType=DECIMAL}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{status,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, RegionPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}