package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPoExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface RegionPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @Delete({
        "delete from region_region",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @Insert({
        "insert into region_region (`pid`, `level`, ",
        "`area_code`, `zip_code`, ",
        "`city_code`, `name`, `short_name`, ",
        "`merger_name`, `pinyin`, ",
        "`lng`, `lat`, `status`, ",
        "`creator_id`, `creator_name`, ",
        "`modifier_id`, `modifier_name`, ",
        "`gmt_create`, `gmt_modified`)",
        "values (#{pid,jdbcType=BIGINT}, #{level,jdbcType=TINYINT}, ",
        "#{areaCode,jdbcType=VARCHAR}, #{zipCode,jdbcType=VARCHAR}, ",
        "#{cityCode,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{shortName,jdbcType=VARCHAR}, ",
        "#{mergerName,jdbcType=VARCHAR}, #{pinyin,jdbcType=VARCHAR}, ",
        "#{lng,jdbcType=DECIMAL}, #{lat,jdbcType=DECIMAL}, #{status,jdbcType=TINYINT}, ",
        "#{creatorId,jdbcType=BIGINT}, #{creatorName,jdbcType=VARCHAR}, ",
        "#{modifierId,jdbcType=BIGINT}, #{modifierName,jdbcType=VARCHAR}, ",
        "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(RegionPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @InsertProvider(type=RegionPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(RegionPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @SelectProvider(type=RegionPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="pid", property="pid", jdbcType=JdbcType.BIGINT),
        @Result(column="level", property="level", jdbcType=JdbcType.TINYINT),
        @Result(column="area_code", property="areaCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_name", property="shortName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merger_name", property="mergerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="pinyin", property="pinyin", jdbcType=JdbcType.VARCHAR),
        @Result(column="lng", property="lng", jdbcType=JdbcType.DECIMAL),
        @Result(column="lat", property="lat", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<RegionPo> selectByExample(RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `pid`, `level`, `area_code`, `zip_code`, `city_code`, `name`, `short_name`, ",
        "`merger_name`, `pinyin`, `lng`, `lat`, `status`, `creator_id`, `creator_name`, ",
        "`modifier_id`, `modifier_name`, `gmt_create`, `gmt_modified`",
        "from region_region",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="pid", property="pid", jdbcType=JdbcType.BIGINT),
        @Result(column="level", property="level", jdbcType=JdbcType.TINYINT),
        @Result(column="area_code", property="areaCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_name", property="shortName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merger_name", property="mergerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="pinyin", property="pinyin", jdbcType=JdbcType.VARCHAR),
        @Result(column="lng", property="lng", jdbcType=JdbcType.DECIMAL),
        @Result(column="lat", property="lat", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    RegionPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") RegionPo row, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") RegionPo row, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RegionPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region_region
     *
     * @mbg.generated
     */
    @Update({
        "update region_region",
        "set `pid` = #{pid,jdbcType=BIGINT},",
          "`level` = #{level,jdbcType=TINYINT},",
          "`area_code` = #{areaCode,jdbcType=VARCHAR},",
          "`zip_code` = #{zipCode,jdbcType=VARCHAR},",
          "`city_code` = #{cityCode,jdbcType=CHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`short_name` = #{shortName,jdbcType=VARCHAR},",
          "`merger_name` = #{mergerName,jdbcType=VARCHAR},",
          "`pinyin` = #{pinyin,jdbcType=VARCHAR},",
          "`lng` = #{lng,jdbcType=DECIMAL},",
          "`lat` = #{lat,jdbcType=DECIMAL},",
          "`status` = #{status,jdbcType=TINYINT},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(RegionPo row);
}